version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$vVcgq1.Iv74zeiT1y4JkBOLq7e0Luc.E4981pP2Sx5XRqwWxEPkVu"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/5418297"
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    restart: on-failure:3
