version: "3.7"

services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    environment:
      - MYJD_USER=tuo_user_email
      - MYJD_PASSWORD=la_tua_password
      - MYJD_DEVICE_NAME=NomeDelDispositivo
    volumes:
      - ./config:/opt/JDownloader/cfg
      - ./downloads:/root/Downloads
    ports:
      - 19829:3129
    restart: always
