version: "3.8"
services:
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    ports:
      - "14546:5800" # Porta per l'interfaccia grafica via VNC
    volumes:
      - ${APP_DATA_DIR}/config:/opt/JDownloader/cfg
      - ${APP_DATA_DIR}/downloads:/root/Downloads
    environment:
      - MYJD_USER=tuo_email@example.com
      - MYJD_PASSWORD=la_tua_password
      - MYJD_DEVICE_NAME=nome_del_tuo_dispositivo
