version: '3.3'

services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    ports:
      - "5800:5800"
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/output
    environment:
      - MYJD_USER=your-myjdownloader-username
      - MYJD_PASSWORD=your-myjdownloader-password
    restart: unless-stopped
