---
version: "2"
services:
  pyload:
    image: pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /umbrel/app-data/pyload/config:/config
      - /umbrel/app-data/pyload/downloads:/downloads
    ports:
      - 8800:8000 # Webinterface
      - 9966:9666 # Click 'N' Load
    restart: unless-stopped
