services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /umbrel/app-data/kirito-pyload-ng/config:/config
      - /umbrel/app-data/kirito-pyload-ng/downloads:/downloads
    ports:
      - 29330:29330
      - 26961:26961 #optional
    restart: unless-stopped
