version: "3"

services:
  ariang:
    image: wonderfall/aria2-ariang:latest
    container_name: ariang
    restart: unless-stopped
    ports:
      - "12345:6800" # Porta per aria2 RPC
      - "23456:80" # Porta per AriaNg web interface
    volumes:
      - ${APP_DATA_DIR}/aria2_data:/downloads # Directory per i download
      - ${APP_DATA_DIR}/aria2_config:/config # Directory per la configurazione di aria2
      - ${APP_DATA_DIR}/aria2_session:/aria2.session # File di sessione per aria2
    environment:
      - PUID=1000 # ID utente per i file scaricati (puoi cambiare a seconda del tuo setup)
      - PGID=1000 # ID gruppo per i file scaricati (puoi cambiare a seconda del tuo setup)
      - RPC_SECRET=GX3R3publ1c!?! # Segreto per l'accesso RPC (imposta una password sicura)
    networks:
      - ariang_net

networks:
  ariang_net:
    driver: bridge
